<?php

/**
 * Auto generated by MySQL Workbench Schema Exporter.
 * Version 3.0.3 (doctrine2-annotation) on 2017-04-25 13:11:30.
 * Goto https://github.com/johmue/mysql-workbench-schema-exporter for more
 * information.
 */

namespace Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * Entity\Answer
 *
 * @ORM\Entity(repositoryClass="AnswerRepository")
 * @ORM\Table(name="Answer", indexes={@ORM\Index(name="fk_Answer_QCM1_idx", columns={"IdQuestion"})})
 */
class Answer
{
    /**
     * @ORM\Id
     * @ORM\Column(type="integer", options={"unsigned":true})
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $IdAnswer;

    /**
     * @ORM\Column(name="`Text`", type="string", length=45, nullable=true)
     */
    protected $Text;

    /**
     * @ORM\Column(type="string", length=45, nullable=true)
     */
    protected $Is_answer;

    /**
     * @ORM\Id
     * @ORM\Column(type="integer", options={"unsigned":true})
     */
    protected $IdQuestion;

    /**
     * @ORM\ManyToOne(targetEntity="Question", inversedBy="answers")
     * @ORM\JoinColumn(name="IdQuestion", referencedColumnName="IdQuestion", nullable=false)
     */
    protected $question;

    public function __construct()
    {
    }

    /**
     * Set the value of IdAnswer.
     *
     * @param integer $IdAnswer
     * @return \Entity\Answer
     */
    public function setIdAnswer($IdAnswer)
    {
        $this->IdAnswer = $IdAnswer;

        return $this;
    }

    /**
     * Get the value of IdAnswer.
     *
     * @return integer
     */
    public function getIdAnswer()
    {
        return $this->IdAnswer;
    }

    /**
     * Set the value of Text.
     *
     * @param string $Text
     * @return \Entity\Answer
     */
    public function setText($Text)
    {
        $this->Text = $Text;

        return $this;
    }

    /**
     * Get the value of Text.
     *
     * @return string
     */
    public function getText()
    {
        return $this->Text;
    }

    /**
     * Set the value of Is_answer.
     *
     * @param string $Is_answer
     * @return \Entity\Answer
     */
    public function setIsAnswer($Is_answer)
    {
        $this->Is_answer = $Is_answer;

        return $this;
    }

    /**
     * Get the value of Is_answer.
     *
     * @return string
     */
    public function getIsAnswer()
    {
        return $this->Is_answer;
    }

    /**
     * Set the value of IdQuestion.
     *
     * @param integer $IdQuestion
     * @return \Entity\Answer
     */
    public function setIdQuestion($IdQuestion)
    {
        $this->IdQuestion = $IdQuestion;

        return $this;
    }

    /**
     * Get the value of IdQuestion.
     *
     * @return integer
     */
    public function getIdQuestion()
    {
        return $this->IdQuestion;
    }

    /**
     * Set Question entity (many to one).
     *
     * @param \Entity\Question $question
     * @return \Entity\Answer
     */
    public function setQuestion(Question $question = null)
    {
        $this->question = $question;

        return $this;
    }

    /**
     * Get Question entity (many to one).
     *
     * @return \Entity\Question
     */
    public function getQuestion()
    {
        return $this->question;
    }

    public function __sleep()
    {
        return array('IdAnswer', 'Text', 'Is_answer', 'IdQuestion');
    }
}