<?php

/**
 * Auto generated by MySQL Workbench Schema Exporter.
 * Version 3.0.3 (doctrine2-annotation) on 2017-04-25 13:11:30.
 * Goto https://github.com/johmue/mysql-workbench-schema-exporter for more
 * information.
 */

namespace Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * Entity\UserAnswer
 *
 * @ORM\Entity(repositoryClass="UserAnswerRepository")
 * @ORM\Table(name="User_answer", indexes={@ORM\Index(name="fk_Game_has_Question_Question1_idx", columns={"IdQuestion"}), @ORM\Index(name="fk_Game_has_Question_Game1_idx", columns={"IdGame"})})
 */
class UserAnswer
{
    /**
     * @ORM\Id
     * @ORM\Column(type="integer", options={"unsigned":true})
     */
    protected $IdGame;

    /**
     * @ORM\Id
     * @ORM\Column(type="integer", options={"unsigned":true})
     */
    protected $IdQuestion;

    /**
     * @ORM\Column(type="string", length=45, nullable=true)
     */
    protected $UserAnswer;

    /**
     * @ORM\ManyToOne(targetEntity="Game", inversedBy="userAnswers")
     * @ORM\JoinColumn(name="IdGame", referencedColumnName="IdGame", nullable=false)
     */
    protected $game;

    /**
     * @ORM\ManyToOne(targetEntity="Question", inversedBy="userAnswers")
     * @ORM\JoinColumn(name="IdQuestion", referencedColumnName="IdQuestion", nullable=false)
     */
    protected $question;

    public function __construct()
    {
    }

    /**
     * Set the value of IdGame.
     *
     * @param integer $IdGame
     * @return \Entity\UserAnswer
     */
    public function setIdGame($IdGame)
    {
        $this->IdGame = $IdGame;

        return $this;
    }

    /**
     * Get the value of IdGame.
     *
     * @return integer
     */
    public function getIdGame()
    {
        return $this->IdGame;
    }

    /**
     * Set the value of IdQuestion.
     *
     * @param integer $IdQuestion
     * @return \Entity\UserAnswer
     */
    public function setIdQuestion($IdQuestion)
    {
        $this->IdQuestion = $IdQuestion;

        return $this;
    }

    /**
     * Get the value of IdQuestion.
     *
     * @return integer
     */
    public function getIdQuestion()
    {
        return $this->IdQuestion;
    }

    /**
     * Set the value of UserAnswer.
     *
     * @param string $UserAnswer
     * @return \Entity\UserAnswer
     */
    public function setUserAnswer($UserAnswer)
    {
        $this->UserAnswer = $UserAnswer;

        return $this;
    }

    /**
     * Get the value of UserAnswer.
     *
     * @return string
     */
    public function getUserAnswer()
    {
        return $this->UserAnswer;
    }

    /**
     * Set Game entity (many to one).
     *
     * @param \Entity\Game $game
     * @return \Entity\UserAnswer
     */
    public function setGame(Game $game = null)
    {
        $this->game = $game;

        return $this;
    }

    /**
     * Get Game entity (many to one).
     *
     * @return \Entity\Game
     */
    public function getGame()
    {
        return $this->game;
    }

    /**
     * Set Question entity (many to one).
     *
     * @param \Entity\Question $question
     * @return \Entity\UserAnswer
     */
    public function setQuestion(Question $question = null)
    {
        $this->question = $question;

        return $this;
    }

    /**
     * Get Question entity (many to one).
     *
     * @return \Entity\Question
     */
    public function getQuestion()
    {
        return $this->question;
    }

    public function __sleep()
    {
        return array('IdGame', 'IdQuestion', 'UserAnswer');
    }
}