-- MySQL Script generated by MySQL Workbench
-- 04/26/17 17:08:34
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`User` ;

CREATE TABLE IF NOT EXISTS `mydb`.`User` (
  `IdUser` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  `Surname` VARCHAR(45) NOT NULL,
  `Birthdate` DATE NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  `CV` VARCHAR(45) NULL,
  `Role` VARCHAR(45) NULL,
  `Password` VARCHAR(255) NOT NULL,
  `Gender` TINYINT NULL,
  PRIMARY KEY (`IdUser`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`JobApplication`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`JobApplication` ;

CREATE TABLE IF NOT EXISTS `mydb`.`JobApplication` (
  `IdJobApplication` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  `Timeout` VARCHAR(45) NOT NULL,
  `Quantity` INT NULL DEFAULT 1,
  `Description` VARCHAR(45) NULL,
  PRIMARY KEY (`IdJobApplication`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Question`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Question` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Question` (
  `IdQuestion` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Wording` VARCHAR(45) NULL,
  `Type` VARCHAR(45) NULL,
  `IdJobApplication` INT NOT NULL,
  PRIMARY KEY (`IdQuestion`),
  INDEX `fk_Question_JobApplication1_idx` (`IdJobApplication` ASC),
  CONSTRAINT `fk_Question_JobApplication1`
    FOREIGN KEY (`IdJobApplication`)
    REFERENCES `mydb`.`JobApplication` (`IdJobApplication`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Answer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Answer` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Answer` (
  `IdAnswer` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Text` VARCHAR(45) NULL,
  `Is_answer` VARCHAR(45) NULL,
  `IdQuestion` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`IdAnswer`),
  INDEX `fk_Answer_Question1_idx` (`IdQuestion` ASC),
  CONSTRAINT `fk_Answer_Question1`
    FOREIGN KEY (`IdQuestion`)
    REFERENCES `mydb`.`Question` (`IdQuestion`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Skills`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Skills` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Skills` (
  `IdSkills` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NULL,
  `Type` TINYINT NULL,
  PRIMARY KEY (`IdSkills`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`User_Skills`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`User_Skills` ;

CREATE TABLE IF NOT EXISTS `mydb`.`User_Skills` (
  `IdUser` INT UNSIGNED NOT NULL,
  `IdSkills` INT NOT NULL,
  PRIMARY KEY (`IdUser`, `IdSkills`),
  INDEX `fk_User_has_Skills_Skills1_idx` (`IdSkills` ASC),
  INDEX `fk_User_has_Skills_User1_idx` (`IdUser` ASC),
  CONSTRAINT `fk_User_has_Skills_User1`
    FOREIGN KEY (`IdUser`)
    REFERENCES `mydb`.`User` (`IdUser`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_User_has_Skills_Skills1`
    FOREIGN KEY (`IdSkills`)
    REFERENCES `mydb`.`Skills` (`IdSkills`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Game`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Game` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Game` (
  `IdGame` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Last_play` DATETIME NULL,
  `Score` INT NULL DEFAULT 0,
  `IdJobApplication` INT NOT NULL,
  `Is_finished` TINYINT NULL DEFAULT 0,
  `IdUser` INT UNSIGNED NOT NULL,
  `LastQuestion` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`IdGame`),
  INDEX `fk_Game_JobApplication1_idx` (`IdJobApplication` ASC),
  INDEX `fk_Game_User1_idx` (`IdUser` ASC),
  INDEX `fk_Game_Question1_idx` (`LastQuestion` ASC),
  CONSTRAINT `fk_Game_JobApplication1`
    FOREIGN KEY (`IdJobApplication`)
    REFERENCES `mydb`.`JobApplication` (`IdJobApplication`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Game_User1`
    FOREIGN KEY (`IdUser`)
    REFERENCES `mydb`.`User` (`IdUser`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Game_Question1`
    FOREIGN KEY (`LastQuestion`)
    REFERENCES `mydb`.`Question` (`IdQuestion`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`User_answer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`User_answer` ;

CREATE TABLE IF NOT EXISTS `mydb`.`User_answer` (
  `IdGame` INT UNSIGNED NOT NULL,
  `IdQuestion` INT UNSIGNED NOT NULL,
  `UserAnswer` VARCHAR(45) NULL,
  PRIMARY KEY (`IdGame`, `IdQuestion`),
  INDEX `fk_Game_has_Question_Question1_idx` (`IdQuestion` ASC),
  INDEX `fk_Game_has_Question_Game1_idx` (`IdGame` ASC),
  CONSTRAINT `fk_Game_has_Question_Game1`
    FOREIGN KEY (`IdGame`)
    REFERENCES `mydb`.`Game` (`IdGame`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Game_has_Question_Question1`
    FOREIGN KEY (`IdQuestion`)
    REFERENCES `mydb`.`Question` (`IdQuestion`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
